### ISSUE TITLE
ValueError: Unknown split "330k_train". Should be one of ['train', 'test'].

### ISSUE THREAD

**Issue by Chase-Xuu** [kevinyaobytedance/llm_unlearn#7]
Hello, I have faced a problem and have not seen it in the issues. 

(llm_unlearn) root@5e0bce17bb64:/home/chixu/ELEC631/llm_unlearn# python unlearn_harm.py --model_name=facebook/opt-1.3b --model_save_dir=models/opt1.3b_unlearned --log_file=logs/opt-1.3b-unlearn.log
Traceback (most recent call last):
  File "/home/chixu/ELEC631/llm_unlearn/unlearn_harm.py", line 228, in <module>
    main(args)
  File "/home/chixu/ELEC631/llm_unlearn/unlearn_harm.py", line 56, in main
    train_dataset = load_dataset("PKU-Alignment/PKU-SafeRLHF", split="330k_train")
  File "/home/chixu/anaconda3/envs/llm_unlearn/lib/python3.10/site-packages/datasets/load.py", line 2166, in load_dataset
    ds = builder_instance.as_dataset(split=split, verification_mode=verification_mode, in_memory=keep_in_memory)
  File "/home/chixu/anaconda3/envs/llm_unlearn/lib/python3.10/site-packages/datasets/builder.py", line 1190, in as_dataset
    datasets = map_nested(
  File "/home/chixu/anaconda3/envs/llm_unlearn/lib/python3.10/site-packages/datasets/utils/py_utils.py", line 456, in map_nested
    return function(data_struct)
  File "/home/chixu/anaconda3/envs/llm_unlearn/lib/python3.10/site-packages/datasets/builder.py", line 1220, in _build_single_dataset
    ds = self._as_dataset(
  File "/home/chixu/anaconda3/envs/llm_unlearn/lib/python3.10/site-packages/datasets/builder.py", line 1294, in _as_dataset
    dataset_kwargs = ArrowReader(cache_dir, self.info).read(
  File "/home/chixu/anaconda3/envs/llm_unlearn/lib/python3.10/site-packages/datasets/arrow_reader.py", line 240, in read
    files = self.get_file_instructions(name, instructions, split_infos)
  File "/home/chixu/anaconda3/envs/llm_unlearn/lib/python3.10/site-packages/datasets/arrow_reader.py", line 213, in get_file_instructions
    file_instructions = make_file_instructions(
  File "/home/chixu/anaconda3/envs/llm_unlearn/lib/python3.10/site-packages/datasets/arrow_reader.py", line 130, in make_file_instructions
    absolute_instructions = instruction.to_absolute(name2len)
  File "/home/chixu/anaconda3/envs/llm_unlearn/lib/python3.10/site-packages/datasets/arrow_reader.py", line 653, in to_absolute
    return [_rel_to_abs_instr(rel_instr, name2len) for rel_instr in self._relative_instructions]
  File "/home/chixu/anaconda3/envs/llm_unlearn/lib/python3.10/site-packages/datasets/arrow_reader.py", line 653, in <listcomp>
    return [_rel_to_abs_instr(rel_instr, name2len) for rel_instr in self._relative_instructions]
  File "/home/chixu/anaconda3/envs/llm_unlearn/lib/python3.10/site-packages/datasets/arrow_reader.py", line 465, in _rel_to_abs_instr
    raise ValueError(f'Unknown split "{split}". Should be one of {list(name2len)}.')
ValueError: Unknown split "330k_train". Should be one of ['train', 'test'].

**Comment by uyenlk** [comment]
I had the same problem. Go to the unlearn_harm.py file and change the split from '330k_train' to 'train'.

**Comment by moro0v0** [comment]
BRO，I checked and tested the results myself, and found that firstly, bad_rass kept jumping between 2 and 3 during the training process, without any significant increase. In addition, I also found that using its template itself does not output content for the same issue. Excuse me, are you still researching this issue? Can you provide contact information for communication? thank you!

**Comment by yeong-ha-kim** [comment]
change code in "utils.py"

`def create_pku_dataloader_from_dataset(tokenizer, dataset, fraction=1.0, batch_size=4):
    """
    Given the PKU dataset, create the dataloader on the unlearned harmful Q&A pairs.

    Args:
        tokenizer: Tokenizer.
        dataset: Loaded PKU dataset.
        fraction: <1 will do downsampling.
        batch_size: Batch size.

    Returns:
        Data loader of PKU harmful Q&A pairs.
    """

    # Preproccess function.
    def preproccess(examples):
        """
        Input: Dict[List]
        Output: Dict[List]
        """
        results = {"input_ids": [], "attention_mask": [], "start_locs": []}

        for i in range(len(examples["prompt"])):
            # Subsample if needed.
            if random.random() > fraction:
                continue

            prompt = examples["prompt"][i]
            response = examples["response"][i]

            # Add all responses to results or skip if none.
            text = f"### Question: {prompt}\n ### Answer: {response}"
            tokenized = tokenizer(text, truncation=True, padding="max_length")
            results["input_ids"].append(tokenized["input_ids"])
            results["attention_mask"].append(tokenized["attention_mask"])
            # Calculate start idx for answer
            test_text = f"### Question: {prompt}\n ### Answer: "
            test_tokenized = tokenizer(
                test_text, truncation=True, padding="max_length"
            )
            results["start_locs"].append(len(test_tokenized["input_ids"]) - 1)

        return results
    
    # Combine 1 : n QA format to 1 : 1 
    dataset_df = dataset.to_pandas()
    new_datasets = []
    for idx in tqdm(range(len(dataset_df))):
        row = dataset_df.iloc[idx]
        prompt = row["prompt"]

        # Add only bad samples.
        harmful_answers = []
        if not row["is_response_0_safe"]:
            harmful_answers.append(row["response_0"])
        if not row["is_response_1_safe"]:
            harmful_answers.append(row["response_1"])
        #end if

        for response in harmful_answers:
            new_datasets.append({"prompt" : prompt, "response" : response})

    # Huggingface Dataset convert
    new_datasets = pd.DataFrame(new_datasets)
    new_datasets = Dataset.from_pandas(new_datasets)

    # update dataset
    dataset = new_datasets

    # Need to drop all original columns to emit more than one row for each original row https://huggingface.co/docs/datasets/about_map_batch#input-size-output-size.
    dataset = dataset.map(
        preproccess,
        batched=True,
        remove_columns=[
            "prompt",
            "response"
        ]
    )
    dataset.set_format(
        type="torch", columns=["input_ids", "attention_mask", "start_locs"]
    )

    # Add labels and make it data loader.
    data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

    dataloader = torch.utils.data.DataLoader(
        dataset, batch_size=batch_size, collate_fn=data_collator
    )

    return dataloader
`

and change in "unlearn_harm.py"
`# Load harmful data.
    train_dataset = load_dataset("PKU-Alignment/PKU-SafeRLHF")['train']
    train_bad_loader = create_pku_dataloader_from_dataset(
        tokenizer, train_dataset, batch_size=args.batch_size
    )
`

it will be works.

**Comment by yeong-ha-kim** [comment]
change in utils.py

```
def create_pku_dataloader_from_dataset(tokenizer, dataset, fraction=1.0, batch_size=4):
    """
    Given the PKU dataset, create the dataloader on the unlearned harmful Q&A pairs.

    Args:
        tokenizer: Tokenizer.
        dataset: Loaded PKU dataset.
        fraction: <1 will do downsampling.
        batch_size: Batch size.

    Returns:
        Data loader of PKU harmful Q&A pairs.
    """

    # Preproccess function.
    def preproccess(examples):
        """
        Input: Dict[List]
        Output: Dict[List]
        """
        results = {"input_ids": [], "attention_mask": [], "start_locs": []}

        for i in range(len(examples["prompt"])):
            # Subsample if needed.
            if random.random() > fraction:
                continue

            prompt = examples["prompt"][i]
            response = examples["response"][i]

            # Add all responses to results or skip if none.
            text = f"### Question: {prompt}\n ### Answer: {response}"
            tokenized = tokenizer(text, truncation=True, padding="max_length")
            results["input_ids"].append(tokenized["input_ids"])
            results["attention_mask"].append(tokenized["attention_mask"])
            # Calculate start idx for answer
            test_text = f"### Question: {prompt}\n ### Answer: "
            test_tokenized = tokenizer(
                test_text, truncation=True, padding="max_length"
            )
            results["start_locs"].append(len(test_tokenized["input_ids"]) - 1)

        return results
    
    # Combine 1 : N QA dataset to 1 : 1 
    dataset_df = dataset.to_pandas()
    new_datasets = []
    for idx in tqdm(range(len(dataset_df))):
        row = dataset_df.iloc[idx]
        prompt = row["prompt"]

        # Add only bad samples.
        harmful_answers = []
        if not row["is_response_0_safe"]:
            harmful_answers.append(row["response_0"])
        if not row["is_response_1_safe"]:
            harmful_answers.append(row["response_1"])
        #end if

        for response in harmful_answers:
            new_datasets.append({"prompt" : prompt, "response" : response})

    # Huggingface Dataset convert
    new_datasets = pd.DataFrame(new_datasets)
    new_datasets = Dataset.from_pandas(new_datasets)

    # update dataset
    dataset = new_datasets

    # Need to drop all original columns to emit more than one row for each original row https://huggingface.co/docs/datasets/about_map_batch#input-size-output-size.
    dataset = dataset.map(
        preproccess,
        batched=True,
        remove_columns=[
            "prompt",
            "response"
        ]
    )
    dataset.set_format(
        type="torch", columns=["input_ids", "attention_mask", "start_locs"]
    )

    # Add labels and make it data loader.
    data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

    dataloader = torch.utils.data.DataLoader(
        dataset, batch_size=batch_size, collate_fn=data_collator
    )

    return dataloader
```

and change code in unlearn_harm.py
```
# Load harmful data.
    train_dataset = load_dataset("PKU-Alignment/PKU-SafeRLHF")['train']
    train_bad_loader = create_pku_dataloader_from_dataset(
        tokenizer, train_dataset, batch_size=args.batch_size
    )
```

it will be work

**Comment by Zhang-byte-plus** [comment]
> I had the same problem. Go to the unlearn_harm.py file and change the split from '330k_train' to 'train'.

Hey bro! I followed your suggestion to change the split from '330k_train' to 'train' in the unlearn_harm.py file, then retried the run—but it failed again. Are you still looking into this issue? If you fixed it, could you let me know how you did it?

**Comment by moro0v0** [comment]
this project is shit cant work at all.thx



---Original---
From: ***@***.***&gt;
Date: Sun, Jan 25, 2026 17:52 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kevinyaobytedance/llm_unlearn] ValueError: Unknown split"330k_train". Should be one of ['train', 'test']. (Issue #7)


Zhang-byte-plus left a comment (kevinyaobytedance/llm_unlearn#7)
  
I had the same problem. Go to the unlearn_harm.py file and change the split from '330k_train' to 'train'.
  
Hey bro! I followed your suggestion to change the split from '330k_train' to 'train' in the unlearn_harm.py file, then retried the run—but it failed again. Are you still looking into this issue? If you fixed it, could you let me know how you did it?
